README.md

Assalamualaikum, Pak.
Izin melakukan sedikit perbaikan serta penambahan pada dokumentasi.

feat: Perbaikan serta penambahan dokumentasi.

---

resources/views/public_reports/in_months.blade.php
resources/views/public_reports/in_out.blade.php
resources/views/public_reports/in_weeks.blade.php

PR ini berkaitan dengan issue https://github.com/buku-masjid/buku-masjid/issues/12

Task 12: Fix request query in button not showing this month

---

README.md
composer.json
composer.lock
database/seeders/DefaultCatergoryTableSeeder.php

Pada PR ini, kita membuat 1 paket demo data generator https://github.com/buku-masjid/demo-data, kemudian menjadikannya sebagai dev-dependency.
- https://github.com/buku-masjid/demo-data/issues/1

Demo Data Task 1: Demo Data Generator

---

app/Console/Kernel.php
app/Helpers/functions.php
app/Http/Controllers/DatabaseBackupController.php
app/Providers/AuthServiceProvider.php
resources/lang/en/database_backup.php
resources/lang/id/database_backup.php
resources/views/database_backups/forms.blade.php
resources/views/database_backups/index.blade.php
resources/views/layouts/settings.blade.php
routes/web.php
tests/Unit/Policies/CustomPermissionTest.php

Pada PR ini, kita membuat interface untuk file backup database.
- #3

Task 3: Pengelolaan File Backup Database

---

app/Http/Controllers/BankAccountController.php
app/Http/Controllers/BookController.php
app/Http/Controllers/CategoriesController.php
app/Http/Controllers/FridayLecturingScheduleController.php
app/Http/Controllers/LecturingScheduleController.php
app/Http/Controllers/MasjidProfileController.php
app/Policies/BankAccountPolicy.php
app/Policies/BookPolicy.php
app/Policies/CategoryPolicy.php
app/Policies/LecturingSchedulePolicy.php
app/Policies/TransactionPolicy.php
app/Providers/AuthServiceProvider.php
resources/views/books/index.blade.php
resources/views/layouts/_top_nav_active_book.blade.php
resources/views/layouts/partials/top_nav.blade.php
resources/views/layouts/settings.blade.php
resources/views/masjid_profile/show.blade.php
tests/Unit/Policies/BankAccountPolicyTest.php
tests/Unit/Policies/BookPolicyTest.php
tests/Unit/Policies/CategoryPolicyTest.php
tests/Unit/Policies/CustomPermissionTest.php
tests/Unit/Policies/LecturingSchedulePolicyTest.php

Pada PR ini, kita melakukan improvement hak akses user ke beberapa fitur di sistem buku masjid.
- #20

Task 20: Hak Akses User

---

app/Http/Controllers/ReportsController.php
resources/lang/en/report.php
resources/lang/id/report.php
resources/views/layouts/print.blade.php
resources/views/reports/in_months_pdf.blade.php
resources/views/reports/in_out_pdf.blade.php
resources/views/reports/in_weeks_pdf.blade.php
resources/views/reports/partials/letterhead.blade.php

Pada task ini, kita ingin membuat Kop Surat pada halaman laporan PDF agar menampilkan nama dan alamat masjid di atas judul laporan.
- Resolve #22 
Assalamualaikum Mas @nafiesl, pada PR ini selain menambahkan Kop Surat pada halaman laporan PDF, saya juga menambahkan kondisi apabila nama atau alamat masjid nya kosong, Kop Surat nya tidak akan tertampil (tampilannya akan sama seperti tampilan sebelumnya).

Task 22: Kop Surat pada Template PDF

---

app/Http/Controllers/UserController.php
app/Policies/UserPolicy.php
app/User.php
resources/lang/en/book.php
resources/lang/en/category.php
resources/lang/en/lecturing_schedule.php
resources/lang/en/transaction.php
resources/lang/en/user.php
resources/lang/id/book.php
resources/lang/id/category.php
resources/lang/id/lecturing_schedule.php
resources/lang/id/transaction.php
resources/lang/id/user.php
resources/views/layouts/settings.blade.php
resources/views/users/create.blade.php
resources/views/users/edit.blade.php
resources/views/users/index.blade.php
resources/views/users/show.blade.php
routes/web.php
tests/Feature/ManageUserTest.php
tests/Unit/Models/UserTest.php
tests/Unit/Policies/UserPolicyTest.php

Pada PR ini kita membuat fitur pengelolaan user untuk admin
-  https://github.com/buku-masjid/buku-masjid/pull/25
**Daftar User**
**Formulir Input User Baru**
**Formulir edit User**
**Konfirmasi Hapus User**
**Pencegahan Hapus User yang sudah input data**

Task 25: Pengelolaan User oleh Admin

---

README.md

Pull Request ini untuk memperbaiki Readme bagian Generate Demo data yang belum sesuai. Terimakasih

fix command generate demo data

---

composer.json
composer.lock

setelah saya nambah package ini, sekarang udah bisa run command :
`php artisan test`
`php artisan test --parallel`

Add collision for php artisan test command and --parallel

---

app/Helpers/Setting.php
tests/Unit/Helpers/SettingTest.php

Pada PR ini kita memperbaiki bug yang dilaporkan pada issue #50, yaitu memperbolehkan nilai setting berupa NULL.
- #50 
[Screencast from 15-03-24 06:29:50.webm](https://github.com/buku-masjid/buku-masjid/assets/1853475/36423245-c54b-41f7-bea1-d0c911dc58d0)

Bugfix: Ijinkan nilai setting bernilai null

---

app/Http/Middleware/TrustProxies.php
resources/views/guest/welcome.blade.php
resources/views/layouts/guest.blade.php
tests/Feature/MasjidProfileTest.php

Perbaikan issue https://github.com/buku-masjid/buku-masjid/issues/65

Perbaikan nama masjid pada halaman public

---

app/Http/Controllers/Api/BankAccountController.php
app/Providers/AppServiceProvider.php
resources/lang/en/bank_account.php
resources/lang/id/bank_account.php
resources/views/bank_accounts/show.blade.php
resources/views/guest/donate.blade.php
resources/views/masjid_profile/edit.blade.php
routes/api.php

Pada pull request ini, kita membuat fitur Upload Gambar QRIS pada masing-masing rekening bank. Kemudian ditampilkan pada halaman publik di menu Infaq. Tujuannya untuk mempermudah jamaah yang ingin berinfaq.
- Tidak ada
Berikut langkah upload QRIS per Rekening Bank
1. Login sebagai admin, klik menu **Rek. Bank**
2. Klik **Lihat Detail** pada salah satu rekening bank
3. Pada detail rekening bank, klik **Upload/Ganti Gambar QRIS**
4. Pilih gambar QRIS yang ingin diupload
5. Sesuaikan ukuran gambar QRIS yang akan diupload (crop)
6. Klik Potong dan Simpan
7. Gambar QRIS akan tampil di halaman public menu **Infaq**

Upload Gambar QRIS per Rekening Bank

---

app/Http/Livewire/Books/FinancialSummary.php
composer.json
composer.lock
public/css/app.css
resources/assets/sass/_custom.scss
resources/views/layouts/_top_nav_active_book.blade.php

Pada PR ini kita ingin memperbaiki beberapa issue dependency
- #76 
- #75

Perbaikan Dependency Issue

---

app/Http/Controllers/BookController.php
public/css/app.css
resources/assets/sass/_custom.scss
resources/lang/en/report.php
resources/lang/id/report.php
resources/views/books/edit.blade.php
resources/views/books/show.blade.php
resources/views/reports/finance/all_time/categorized_pdf.blade.php
resources/views/reports/finance/all_time/detailed_pdf.blade.php
resources/views/reports/finance/all_time/summary_pdf.blade.php
resources/views/reports/finance/in_months/categorized_pdf.blade.php
resources/views/reports/finance/in_months/detailed_pdf.blade.php
resources/views/reports/finance/in_months/summary_pdf.blade.php
resources/views/reports/finance/in_weeks/categorized_pdf.blade.php
resources/views/reports/finance/in_weeks/detailed_pdf.blade.php
resources/views/reports/finance/in_weeks/summary_pdf.blade.php
tests/Feature/Books/ManageBookTest.php

Pada PR ini kita membuat fitur penomoran halaman untuk laporan PDF.
- #83 
**Format Periode per Bulan**
**Format Periode per Pekan**
**Format Periode Keseluruhan**
**Pengaturan Buku Kas**

Penomoran Halaman pada Laporan PDF

---

app/Http/Controllers/Reports/FinanceController.php
app/Http/Controllers/TransactionsController.php
app/Http/Livewire/NextMonthButton.php
app/Http/Livewire/PrevMonthButton.php
database/migrations/2018_05_11_202553_create_categories_table.php
database/migrations/2018_05_12_075944_create_transactions_table.php
database/migrations/2023_06_12_225258_create_bank_accounts_table.php
public/css/app.css
resources/assets/sass/_custom.scss
resources/lang/id/transaction.php
resources/views/public_reports/finance/in_months/categorized.blade.php
resources/views/public_reports/finance/in_months/detailed.blade.php
resources/views/public_reports/finance/in_months/summary.blade.php
resources/views/public_reports/finance/in_weeks/categorized.blade.php
resources/views/public_reports/finance/in_weeks/detailed.blade.php
resources/views/public_reports/finance/in_weeks/summary.blade.php

Pada PR ini saya membuat beberapa perbaikan terkait tampilan dan error.
- Tidak ada

Beberapa Perbaikan Tampilan, Error, dan File Migration

---

.env.example
config/features.php
resources/views/guest/welcome.blade.php
resources/views/layouts/guest.blade.php
resources/views/layouts/partials/top_nav.blade.php
routes/web.php

Karena aplikasi buku masjid tidak hanya digunakan oleh masjid, maka kita perlu membuat konfigurasi untuk mematikan dan menyalakan fitur Jadwal Pengajian sesuai kebutuhan. Beberapa pengguna yang bukan masjid/mushalla adalah:
- Sekolah
- Yayasan
- Lembaga
- Media
- Rumah Quran
- Tidak ada
- Env variable `FEATURES_LECTURINGS_IS_ACTIVE=true/false` default true
- Config: `config('feature.lecturings.is_active')`
- Tampilkan menu Pengajian pada halaman admin jika jadwal pengajian aktif
- Tampilkan menu Jadwal pada halaman publik jika jadwal pengajian aktif
- Tampilkan widget jadwal pengajian pada halaman publik jika jadwal pengajian aktif
Jadwal pengajian dimatikan dari file `.env`
Tidak tampil menu Pengajian di halaman admin
Tidak ada menu Jadwal dan Widget Jadwal Pengajian Jadwal Pengajian

Konfigurasi On/Off Fitur Jadwal Pengajian dan Khatib Jumat

---

app/Rules/PhoneNumberRule.php
resources/lang/en/validation.php
resources/lang/id/validation.php
tests/Feature/ManageDonorTest.php

Dari issue #104, nomor hp yang diawali dengan 08xxxx tidak diterima oleh aplikasi whatsapp, sehingga format validasi harus disesuaikan dengan format whatsapp.
- #104

Update Rule Validasi No. Telp Warga sesuai format Whatsapp

---

app/Http/Controllers/TransactionsController.php
app/Models/BankAccountBalance.php
public/js/plugins/number-format.js
resources/lang/en/transaction.php
resources/lang/id/transaction.php
resources/views/bank_accounts/_bank_account_balance_forms.blade.php
resources/views/bank_accounts/show.blade.php
resources/views/donors/transactions/create.blade.php
resources/views/transactions/create.blade.php
resources/views/transactions/edit.blade.php
tests/Unit/Models/BankAccountBalanceTest.php

Pada PR ini, kita membuat agar input angka rupiah otomatis ada pemisahan tiap ribuan.
- Tidak ada
**Pemisahan angka ribuan**

Pemisah Ribuan pada Input Rupiah

---

resources/lang/en/app.php
resources/lang/en/lecturing.php
resources/lang/id/app.php
resources/lang/id/lecturing.php
resources/views/friday_lecturings/edit.blade.php
resources/views/lecturings/edit.blade.php
tests/Feature/Lecturing/LecturingEditTest.php

Pada PR ini, kita merubah istilah pada tombol
Tidak ada
**Sebelum**
**Sesudah**

Perubahan kata pada tombol saat edit pengajian atau khatib

---

app/Http/Controllers/Transactions/FileController.php
app/Http/Requests/Transactions/CreateRequest.php

Perbaikan menambahkan format webp https://t.me/bukumasjid_id/1757
https://github.com/user-attachments/assets/9dc8320b-b64b-40de-adc5-e70f6a2fd1d9

Tambahkan format webp ketika upload transaksi

---

README.md
database/seeders/DefaultCatergoryTableSeeder.php
resources/lang/id/app.php
resources/views/guest/books/index.blade.php

Mengganti kata `infaq` > `infak`

Mengganti kata infaq dengan infak sesuai KBBI

---

app/User.php
database/factories/UserFactory.php
tests/Feature/ManageUserTest.php
tests/Unit/Models/UserTest.php

close #123 
PR ini menyelesaikan issue
- #123 
Checklist 
referensi https://github.com/buku-masjid/buku-masjid/blob/4d691396e615b312cfeabdb8b693b5b9d3d1e6c7/resources/lang/en/app.php#L12
https://github.com/buku-masjid/buku-masjid/blob/4d691396e615b312cfeabdb8b693b5b9d3d1e6c7/resources/lang/id/app.php#L12
Dokumentasi Video
[Daftar User - Buku Masjid Admin.webm](https://github.com/user-attachments/assets/b21f61bc-b848-4375-96a9-3fc6fe388aba)

Fix User Status Update

---

app/Http/Controllers/TransactionsController.php
resources/lang/en/app.php
resources/lang/en/transaction.php
resources/lang/id/app.php
resources/lang/id/transaction.php
resources/views/transactions/create.blade.php
resources/views/transactions/index.blade.php
resources/views/transactions/partials/single_transaction_mobile.blade.php
resources/views/transactions/show.blade.php
tests/Feature/Transactions/TransactionEntryTest.php

Dari masukan salah satu pengguna, ada beberapa transaksi yang sifatnya berulang (seperti insentif pengajian atau jumat), sehingga jika ada fitur duplikat transaksi akan sangat membantu mempermudah proses input transaksi. Implementasinya, setiap transaksi ada tombol utk duplikat, sehingga user tinggal mengisi tanggal atau mengubah deskripsi.
Tombol duplikat pada list transaksi
Tombol duplikat pada detail transaksi

Duplikat Transaksi
